#!/bin/bash

echo "Installing apt dependencies..."
sudo apt install -y python3 build-essential libssl-dev libffi-dev python-dev pip
echo "Done"

echo "Creating virtual environment..."
python3 -m venv venv
echo "Done"

echo "Installing pips..."
. venv/bin/activate
pip install -r required.txt
deactivate
echo "Done"

echo "Installing..."
cat << EOF > NotHydra
#!/bin/bash
$( pwd )/venv/bin/python NotHydra.py "$@"
EOF
sudo ln -s "$( pwd )/NotHydra" "/usr/bin"
echo "Installation complete!"
echo
